### ISSUE TITLE
Severe sepses - incorrect code

### ISSUE THREAD

**Issue by friedrich-heuser** [ONSdigital/icd11-ons-english-dictionary#1]
117,1H0Z,,Severe sepsis,,2022,9999,13/10/2023,NA,,

Seems to be a wrong code for sepsis. It should be 1G40.

Author: Friedrich Heuser
Institution:  BfArM
[

**Comment by PaulHarrisONS** [comment]
Locally we've changed this to 1G40&XS25, but we're not ready to release that yet because we're not sure this is right. In ICD-10 'Severe sepsis' indexes to [R65.1](https://icd.who.int/browse10/2019/en#/R65.1), which would be [MG46](https://icd.who.int/dev11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f973161881) in ICD-11. Do you have an opinion on this?

**Comment by friedrich-heuser** [comment]
Hi Paul,

The coding tool for ICD-11 has no entry for ‘severe sepsis’. ‘SIRS of infectious origin’ went to 1H0Z.

***@***.***

We in Germany we did not follow the WHO index for severe sepsis. We used A419.

The concept of SIRS has changed. So we think ‘severe sepsis’ should be coded at 1G40&XS25, also SIRS of infectious origin. Ulrich will take this issue to the small CSAC group.

Best wishes,
Freddy


Von: Paul Harris ***@***.***>
Gesendet: Mittwoch, 14. Februar 2024 09:50
An: ONSdigital/icd11-ons-english-dictionary ***@***.***>
Cc: Heuser, Friedrich ***@***.***>; Author ***@***.***>
Betreff: Re: [ONSdigital/icd11-ons-english-dictionary] Severe sepses - incorrect code (Issue #1)


Locally we've changed this to 1G40&XS25, but we're not ready to release that yet because we're not sure this is right. In ICD-10 'Severe sepsis' indexes to R65.1<https://icd.who.int/browse10/2019/en#/R65.1>, which would be MG46<https://icd.who.int/dev11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f973161881> in ICD-11. Do you have an opinion on this?

**Comment by PaulHarrisONS** [comment]
That's a convincing case, thank you. I'll upload the change as soon as we've validated the latest dictionary

**Comment by PaulHarrisONS** [comment]
Resolved in 1b4c518cf47fa7cb335ba6e2db6dce928532369e. https://github.com/ONSdigital/icd11-ons-english-dictionary/blob/1b4c518cf47fa7cb335ba6e2db6dce928532369e/Dictionary.txt#L121
